# Generated by Django 5.0.3 on 2025-06-24 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=75)),
                ('telefone', models.IntegerField(max_length=11)),
                ('telefone_whatsapp', models.BooleanField()),
                ('endereco', models.CharField(max_length=100)),
                ('numero_endereco', models.CharField(max_length=5)),
                ('cidade', models.CharField(max_length=23)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.IntegerField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_envio', models.CharField(max_length=50)),
                ('texto', models.TextField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='send_email.cliente')),
            ],
        ),
    ]
